
import { ToastContainer } from "react-toastify";
import "./globals.css";
import { Assistant } from 'next/font/google';
import GlobalProvider from "@/components/Application/GlobalProvider";



const assistantFont = Assistant({
  weight:['400','500','600','700','800'],
  subsets:['latin'],
  display:'swap',
  variable:"--font-assistant"
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${assistantFont.variable} antialiased`}>
      
          <GlobalProvider>
            <div id="toast-root" className="toast-overlay">
              <ToastContainer />
            </div>
            {children}
          </GlobalProvider>
      
      </body>
    </html>
  );
}
